### PR TITLE
Updates LICENSE to DoNoHarm

### PR DESCRIPTION
**Pull request by jasongwartz**

### CODE REVIEW

**Comment by LostCrew** [comment]
@jasongwartz 
1. Needs to be updated with details and trimmed out, like in https://github.com/ecosia/eslint-config/blob/master/LICENSE
2. Misses some [files](https://github.com/ecosia/bazel_rules_nodejs_contrib/search?q=copyright&unscoped_q=copyright)

**Comment by LostCrew** [comment]
@jasongwartz shall we give this some quick love?

**Comment by jasongwartz** [comment]
Just updated the license to latest version, but not sure which way to go with the copyright notices in files. If it were me, I'd strip them out (I don't think we need copyright on anything, and we don't need to additionally have the apache license as well), but I'm not certain.

**Comment by jasongwartz** [comment]
eg: https://github.com/ecosia/bazel_rules_nodejs_contrib/blob/f1cd003d3da7a4bf7b42064decea1a66fee09a87/internal/BUILD.bazel#L1
https://github.com/ecosia/bazel_rules_nodejs_contrib/blob/76a7d3a13f78d35744d264f11be1bf511ae00c3b/internal/json_to_js/parser.js#L3

**Comment by LostCrew** [comment]
@jasongwartz I agree, we totally may take them out

**Comment by LostCrew** [comment]
@jasongwartz We shall try to complete this in reasonable time, it's quite a while that it's open now

**Comment by LostCrew** [comment]
Closing due to inactivity

**Pull request closed without merging**
